{-# LANGUAGE BlockArguments #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE RecordWildCards #-}
{-|
Module      : Data.RBP.DataLoader
Description : Load real PESTICIDE_DB and EVAL_BOX data from JSON files.

Loads data/pesticides.json and data/eval_boxes.json (generated by
scripts/convert_js_data.py from the JS source files) and converts
them into the algebraic types defined in Data.RBP.Types.

File resolution strategy (tries each in order):
  1. ./data/pesticides.json                (CWD-relative)
  2. <exe-dir>/../../data/pesticides.json  (relative to executable)
  3. Hard-coded repo path fallback
-}
{-# LANGUAGE ScopedTypeVariables #-}
module Data.RBP.DataLoader
  ( loadPesticides
  , loadEvalBoxes
  , samplePesticidesFallback
  , sampleEvalBoxesFallback
  ) where

import Data.Aeson
import Data.Aeson.Types (Parser)
import Data.Aeson.KeyMap (KeyMap)
import qualified Data.Aeson.KeyMap as KM
import Data.Aeson.Key (fromString)
import qualified Data.ByteString.Lazy as BL
import qualified Data.Text as T
import qualified Data.Vector as Vec
import Data.HashMap.Strict (HashMap)
import qualified Data.HashMap.Strict as HM
import Data.Maybe (mapMaybe)
import Data.RBP.Types
import System.Directory (doesFileExist, getCurrentDirectory)
import System.FilePath ((</>), takeFileName)
import System.IO (stderr, hPutStrLn)

------------------------------------------------------------------------------
-- Field extraction helpers
------------------------------------------------------------------------------

getField :: Value -> String -> Parser Value
getField (Object o) k =
  case KM.lookup (fromString k) o of
    Just v  -> return v
    Nothing -> fail $ "missing key: " ++ k
getField v _ = fail $ "expected Object, got " ++ showTypeName v

showTypeName :: Value -> String
showTypeName Null        = "null"
showTypeName (Bool _)    = "bool"
showTypeName (String _)  = "string"
showTypeName (Number _)  = "number"
showTypeName (Array _)   = "array"
showTypeName (Object _)  = "object"

------------------------------------------------------------------------------
-- Manual parsers (avoid aeson Key / type ambiguity issues)
------------------------------------------------------------------------------

parsePesticideId :: Value -> Parser PesticideId
parsePesticideId = \case
  String s -> return (PID (T.unpack s))
  v        -> fail $ "expected string for PesticideId, got " ++ showTypeName v

parsePesticide :: Value -> Parser Pesticide
parsePesticide v = case v of
  Object _ -> do
    pid            <- parsePesticideId =<< getField v "id"
    pname          <- parseString =<< getField v "name"
    targetVector   <- parseTargetVector =<< getField v "targetVector"
    phiDays        <- parsePhiDays =<< getField v "phiDays"
    toxicityClass  <- parseToxicity =<< getField v "toxicityClass"
    systemCode     <- parseString =<< getField v "systemCode"
    system         <- parseString =<< getField v "system"
    mixingBanTargets <- parseStringList =<< getField v "mixingBanTargets"
    maxApplications <- parseMaxApps =<< getField v "maxApplications"
    return Pesticide
      { pid = pid
      , pname = pname
      , targetVector = targetVector
      , maxApplications = maxApplications
      , phiDays = phiDays
      , toxicityClass = toxicityClass
      , systemCode = systemCode
      , system = system
      , mixingBanTargets = mixingBanTargets
      }
  _ -> fail "pesticide must be an object"

parseString :: Value -> Parser String
parseString = \case
  String s -> return (T.unpack s)
  v        -> fail $ "expected string, got " ++ showTypeName v

parseStringList :: Value -> Parser [String]
parseStringList = \case
  Array arr -> mapM (\v -> case v of String s -> return (T.unpack s); _ -> fail "element must be string") (Vec.toList arr)
  v        -> fail $ "expected array of strings, got " ++ showTypeName v

parseTargetVector :: Value -> Parser EntryVector
parseTargetVector v = case v of
  Array arr -> parseDoubleList (Array arr) >>= \ds ->
    let ints = map (fromIntegral . round) ds
    in case mkEntryVector ints of
         Just ev -> return ev
         Nothing -> fail $ "targetVector must have 10 elements, got " ++ show (length ints)
  _ -> fail "targetVector must be an array"

parsePhiDays :: Value -> Parser Int
parsePhiDays v = case v of
  Number n -> return (round n)
  _ -> fail "phiDays must be a number"

parseToxicity :: Value -> Parser ToxicityClass
parseToxicity v = case v of
  String s ->
    case T.unpack s of
      "劇物" -> return HighlyToxic
      "毒物" -> return Toxic
      _      -> return NonToxic
  _ -> fail "toxicityClass must be a string"

parseMaxApps :: Value -> Parser Int
parseMaxApps v = case v of
  Number n -> return (round n)
  String s ->
    case T.unpack s of
      "inf" -> return (1000000)  -- represent infinity as a large number
      _     -> fail $ "maxApplications: invalid infinity value " ++ show s
  _ -> fail "maxApplications must be a number or 'inf'"

instance FromJSON Pesticide where
  parseJSON = parsePesticide

------------------------------------------------------------------------------
-- EvalBox loading
------------------------------------------------------------------------------

data RawEvalBox = RawEvalBox
  { rbVector :: [Double]
  , rbName   :: String
  } deriving (Show)

parseRawEvalBox :: Value -> Parser RawEvalBox
parseRawEvalBox v = case v of
  Object _ -> do
    rbVector <- parseDoubleList =<< getField v "vector"
    rbName   <- parseString =<< getField v "name"
    return RawEvalBox
      { rbVector = rbVector
      , rbName = rbName
      }
  _ -> fail "eval box must be an object"

parseDoubleList :: Value -> Parser [Double]
parseDoubleList = \case
  Array arr -> return (map (\v -> case v of Number n -> realToFrac n; _ -> 0) (Vec.toList arr))
  v        -> fail $ "expected array of numbers, got " ++ showTypeName v

instance FromJSON RawEvalBox where
  parseJSON = parseRawEvalBox

------------------------------------------------------------------------------
-- File resolution: try multiple candidate paths
------------------------------------------------------------------------------

firstExisting :: [FilePath] -> IO (Maybe FilePath)
firstExisting [] = return Nothing
firstExisting (p:ps) = do
  exists <- doesFileExist p
  if exists then return (Just p) else firstExisting ps

dataFilePath :: String -> IO (Maybe FilePath)
dataFilePath filename = do
  cwd <- getCurrentDirectory
  let candidates =
        [ cwd </> "data" </> filename
        , cwd </> ".." </> "data" </> filename
        , cwd </> ".." </> ".." </> "data" </> filename
        , "/home/ko_matsuyama/app/STB/data" </> filename
        ]
  firstExisting candidates

------------------------------------------------------------------------------
-- Generic loader
------------------------------------------------------------------------------

loadFromFile :: forall a. FromJSON a => FilePath -> IO a
loadFromFile path = do
  content <- BL.readFile path
  case (decode content :: Maybe a) of
    Just a  -> return a
    Nothing -> error $ "Failed to parse " ++ takeFileName path ++ " (expected: [Pesticide] or HashMap)"

loadPesticides :: IO [Pesticide]
loadPesticides = do
  path <- dataFilePath "pesticides.json"
  case path of
    Just p  -> loadFromFile p
    Nothing -> do
      hPutStrLn stderr "WARNING: pesticides.json not found, using sample data (13 agents)"
      return samplePesticidesFallback

loadEvalBoxes :: IO [EvalBox]
loadEvalBoxes = do
  path <- dataFilePath "eval_boxes.json"
  case path of
    Just p  -> loadEvalFromFile p
    Nothing -> do
      hPutStrLn stderr "WARNING: eval_boxes.json not found, using sample data (7 boxes)"
      return sampleEvalBoxesFallback

loadEvalFromFile :: FilePath -> IO [EvalBox]
loadEvalFromFile path = do
  content <- BL.readFile path
  let result = parseEvalBoxes content
  case result of
    Just boxes -> return boxes
    Nothing    -> error $ "Failed to parse eval_boxes.json: " ++ path

parseEvalBoxes :: BL.ByteString -> Maybe [EvalBox]
parseEvalBoxes s = do
  obj <- decode s :: Maybe (HashMap String RawEvalBox)
  return $ mapMaybe parseOneBox (HM.toList obj)
  where
    parseOneBox (eid, edata) = do
      vec <- mkEntryVector (map (fromIntegral . round) (rbVector edata))
      return EvalBox { ebId = EBId eid, ebVector = vec, ebName = rbName edata }

------------------------------------------------------------------------------
-- Sample fallback data (used when JSON files are unavailable)
------------------------------------------------------------------------------

samplePesticidesFallback :: [Pesticide]
samplePesticidesFallback =
  [ Pesticide (PID "P01") "Berquest"     (mkEv [1,1,1,0,0,0,0,0,0,0]) 3  7 NonToxic  "QoI"  "QoI系" []
  , Pesticide (PID "P15") "Benepia"      (mkEv [0,1,1,0,0,0,0,0,0,0]) 2 14 NonToxic  "QoI"  "QoI系" []
  , Pesticide (PID "P21") "G-Fine"       (mkEv [0,1,1,0,0,0,0,0,0,0]) 2 14 NonToxic  "DMI"  "DMI系" []
  , Pesticide (PID "P38") "BenLate"      (mkEv [0,1,1,0,0,0,0,0,0,0]) 2 28 NonToxic  "MBC"  "MBC系" []
  , Pesticide (PID "P47") "Larry"        (mkEv [0,0,0,1,0,0,0,0,0,0]) 3  7 NonToxic  "SA"   "SA系"  []
  , Pesticide (PID "P49") "Agromek"      (mkEv [0,0,0,1,0,1,0,0,0,0]) 2 14 NonToxic  "Amine" "アミン系" []
  , Pesticide (PID "P53") "Coromite"     (mkEv [0,0,0,1,0,0,0,0,0,0]) 2  7 NonToxic  "Thermo" "サーモ系" []
  , Pesticide (PID "P54") "StarMite"     (mkEv [0,0,0,1,0,0,0,0,0,0]) 2  7 NonToxic  "Thermo" "サーモ系" []
  , Pesticide (PID "P41") "Afirm"        (mkEv [0,0,0,0,0,1,0,0,0,0]) 2  7 NonToxic  "Diamide" "ジアミド系" []
  , Pesticide (PID "P42") "Kotetsu"      (mkEv [0,0,0,0,0,1,0,0,0,0]) 2 14 NonToxic  "Diamide" "ジアミド系" []
  , Pesticide (PID "P05") "Topaz"        (mkEv [0,1,1,0,0,0,0,0,0,0]) 2 21 NonToxic  "DMI"  "DMI系" []
  , Pesticide (PID "P10") "Ablame"       (mkEv [0,0,0,1,0,1,0,0,0,0]) 2 14 HighlyToxic "Amine" "アミン系" ["アミン系"]
  , Pesticide (PID "P20") "Dantron"      (mkEv [1,0,0,0,1,0,0,0,0,0]) 2 14 NonToxic  "Sulfur" "有機硫黄系" []
  ]

sampleEvalBoxesFallback :: [EvalBox]
sampleEvalBoxesFallback =
  [ EvalBox (EBId "EB-01")  (mkEv [1,0,0,0,0,0,0,0,0,0]) "Anthracnose only"
  , EvalBox (EBId "EB-02")  (mkEv [0,1,0,0,0,0,0,0,0,0]) "Gray mold only"
  , EvalBox (EBId "EB-03")  (mkEv [0,0,1,0,0,0,0,0,0,0]) "Powdery mildew only"
  , EvalBox (EBId "EB-04")  (mkEv [0,0,0,1,0,0,0,0,0,0]) "Spider mite only"
  , EvalBox (EBId "EB-08")  (mkEv [0,1,0,1,0,0,0,0,0,0]) "Gray mold + Spider mite"
  , EvalBox (EBId "EB-19")  (mkEv [0,1,1,0,1,0,0,0,0,0]) "Gray mold + Powdery mildew + Cutworm"
  , EvalBox (EBId "EB-22")  (mkEv [1,1,1,0,1,1,0,0,1,1]) "Complex multi-disease"
  ]

mkEv :: [Int] -> EntryVector
mkEv xs = case mkEntryVector xs of
  Just v  -> v
  Nothing -> error $ "mkEv: expected 10 ints, got " ++ show (length xs)
